### ISSUE TITLE
Fix lagging when updating the file status

### ISSUE THREAD

**Issue by ddobrev** [yysun/Git-Source-Control-Provider#116] opened 2014-08-31 13:51 UTC
This bug appeared more than a year ago. It is particularly annoying because the first versions of GitSCC did not have it at all. When is it going to be fixed?

By the way, is the project in general still maintained?

**Comment by sharwell** [comment] 2014-08-31 16:21
The delay is due to a progressive back-off implemented to prevent the extension from having a detrimental performance impact when used with very large projects. See related issue #28 and the fix implemented in #48.

Issue #51 should improve the situation.

Closing as a duplicate of #51.

**Closed as completed by sharwell** 2014-08-31 16:21 UTC
Labels: status:duplicate

**Comment by ddobrev** [comment] 2014-08-31 18:13
@sharwell The version I use is the latest one from codeplex - December 2013. That is, the fix for #51 has been included but there is significant lag nevertheless. Is it possible to fix it in a way that would refresh the status immediately as in those early versions?

**Comment by sharwell** [comment] 2014-08-31 18:31
Issue #51 has not been implemented to date.

**Comment by ddobrev** [comment] 2014-08-31 18:52
@sharwell sorry I was confused by the "Closed" mark next to the reference, the issue itself really is open. Could you please give an estimation how soon it will be fixed?

**Comment by ddobrev** [comment] 2015-02-27 17:21
Is this bug even going to be fixed? Has this project been abandoned?
